-   name: Setup codingbrain environment
    hosts: all
    vars:
        source_dir: /vagrant
    become_user: vagrant
    tasks:
      
    - name: clone frontend soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-frontend.git
        dest: "{{ source_dir }}/frontend"
      
    - name: clone backend soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-backend.git
        dest: "{{ source_dir }}/backend"
        
    - name: clone worker soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-worker.git
        dest: "{{ source_dir }}/worker"

    - name: install run backend script
      template:
        src: templates/run-backend.sh.j2
        dest: /etc/init/run-backend.sh
        mode: 0711
        
    - name: install run worker script
      template:
        src: templates/run-worker.sh.j2
        dest: /etc/init/run-worker.sh
        mode: 0711

    - name: install woker requirements
      shell: pip3 install -r requirements.txt
      args:
        chdir: "{{ source_dir }}/woker" 
            
        