-   name: Setup codingbrain environment
    hosts: all
    vars:
        frontend_dir: /vagrant/frontend
        backend_dir: /vagrant/backend
        worker_dir: /vagrant/worker
        source_dir: /vagrant
    tasks:
      
    - name: Check for frontend directory     
      stat: 
        path: "{{ frontend_dir }}"
      register: fp

    - name: Check for backend directory     
      stat: 
        path: "{{ backend_dir }}"
      register: bp

    - name: Check for worker directory     
      stat: 
          path: "{{ worker_dir }}"
      register: wp
            
    - name: install run backend script
      template:
        src: templates/run-backend.sh.j2
        dest: "{{ source_dir }}/run-backend.sh"
        mode: 0711
      become: True
      when: not bp.stat.exists
      
    - name: create backend log file
      file:
        path: /var/log/upstart/backend.log
        state: touch
      become: True
      when: not bp.stat.exists

    - name: install run worker script
      template:
        src: templates/run-worker.sh.j2
        dest: "{{ source_dir }}/run-worker.sh"
        mode: 0711
      become: True
      when: not wp.stat.exists

    - name: create worker log file
      file:
        path: /var/log/upstart/worker.log
        state: touch
      become: True
      when: not wp.stat.exists

    - name: clone frontend soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-frontend.git
        dest: "{{ frontend_dir }}"
      when: not fp.stat.exists
      
    - name: clone backend soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-backend.git
        dest: "{{ backend_dir }}"
      when: not bp.stat.exists
        
    - name: clone worker soure
      git:
        repo: https://github.com/thecodingbrain/webscraper-microservices-worker.git
        dest: "{{ worker_dir }}"
      when: not wp.stat.exists